#!/bin/bash

base=~/RustTutorial

cd $base
make
cd files
for file in *.dm
do
        echo "Processing $file"
        cd ..
        ./preprocessor files/$file
        x=${file%.dm}
        mv files/$x.md markdown/
        cd -
done
cd $base