#!/bin/bash

base=~/RustTutorial

cd $base
g++ preprocess.cpp
cd files
for file in *.dm
do
	echo "Processing $file"
	cd ..
	./a.out files/$file
	x=${file%.dm}
	mv files/$x.md markdown/
	cd -
done
cd $base
rm a.out
